name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag charlesmuchogo/locator:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image to Docker Hub
      run: |
        docker push charlesmuchogo/locator:latest
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled

